# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_emotion', models.CharField(blank=True, max_length=5, null=True)),
                ('comment_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('comment_wows', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=50, null=True)),
                ('post_question', models.CharField(blank=True, max_length=200, null=True)),
                ('post_content', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_emotions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wowoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_picture', models.URLField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_achievement', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='wowoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wowoo.Wowoo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowoo.Post'),
        ),
    ]
