# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField(blank=True)),
                ('commentEmotion', models.CharField(max_length=5)),
                ('commentName', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('commentWows', models.IntegerField(default=0)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=50, null=True)),
                ('post_question', models.CharField(blank=True, max_length=200, null=True)),
                ('post_content', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_emotions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='wowoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_picture', models.URLField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_achievement', models.IntegerField(default=0)),
            ],
        ),
    ]
