# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_emotion', models.CharField(blank=True, max_length=5, null=True)),
                ('comment_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('comment_wows', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowoo.Post')),
            ],
        ),
    ]
