# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowoo',
            name='user_achievement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wowoo',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wowoo',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wowoo',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wowoo',
            name='user_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wowoo',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
