# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0002_auto_20161216_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='post_Dialogue',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='post_Num',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='post_Title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
