# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField(blank=True)),
                ('commentEmotion', models.CharField(max_length=5)),
                ('commentName', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('commentWows', models.IntegerField(default=0)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='postDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_num',
            field=models.IntegerField(blank=True),
        ),
    ]
