# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0003_auto_20161228_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['post_Num']},
        ),
    ]
