# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0004_auto_20161229_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.CharField(default=0, max_length=20)),
                ('post_Num', models.CharField(default=0, max_length=20)),
                ('post_Title', models.CharField(default=0, max_length=50)),
                ('post_Dialogue', models.CharField(default=0, max_length=50)),
                ('post_Content', models.DateField()),
                ('post_Date', models.DateTimeField(auto_now_add=True)),
                ('post_Emotion', models.CharField(max_length=5)),
                ('post_Likes', models.IntegerField()),
            ],
            options={
                'ordering': ['post_Num'],
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
