# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0005_auto_20161229_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_Content',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_Likes',
            field=models.IntegerField(default=0),
        ),
    ]
