# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-02 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0003_auto_20161229_2018'),
        ('wowoo', '0005_auto_20161230_1203'),
    ]

    operations = [
    ]
