# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0006_auto_20161229_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_Content',
        ),
    ]
