# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowoo', '0004_post_likes'),
        ('wowoo', '0010_auto_20161230_1625'),
    ]

    operations = [
    ]
